# Auto-generated creature data
creatures = {
    "1st_voa1": {
        "name": "Voana2",
        "type": "Electric",
        "colors": ['yellow', 'green'],
        "size": "medium",
        "weight": 250,
        "height": 5.8,
        "speed_type": "land",
        "home_terrain": "City",
        "abilities": ['lightning zap', 'static shield', 'speed dash'],
        "weaknesses": ['Earth', 'Water'],
        "resistances": ['Electric', 'Air'],
        "aggressiveness": 6,
        "intelligence": 7,
        "friendliness": 5,
        "stats": {
            "strength": 6,
            "speed": 8,
            "defense": 4,
            "agility": 7,
            "stamina": 6,
        },
        "catchphrase": "Shock and roll!",
        "class_period": "1st",
        "student_name": "Max",
        "id": "1st_voa1",
        "terrain_boost_used": False,
    },
    "1st_vua1": {
        "name": "Vuana3",
        "type": "Electric",
        "colors": ['yellow', 'green'],
        "size": "medium",
        "weight": 250,
        "height": 5.8,
        "speed_type": "land",
        "home_terrain": "City",
        "abilities": ['lightning zap', 'static shield', 'speed dash'],
        "weaknesses": ['Earth', 'Water'],
        "resistances": ['Electric', 'Air'],
        "aggressiveness": 6,
        "intelligence": 7,
        "friendliness": 5,
        "stats": {
            "strength": 6,
            "speed": 8,
            "defense": 4,
            "agility": 7,
            "stamina": 6,
        },
        "catchphrase": "Shock and roll!",
        "class_period": "1st",
        "student_name": "Max",
        "id": "1st_vua1",
        "terrain_boost_used": False,
    },
    "1st_tig1": {
        "name": "tiguana4",
        "type": "Electric",
        "colors": ['yellow', 'green'],
        "size": "medium",
        "weight": 250,
        "height": 5.8,
        "speed_type": "land",
        "home_terrain": "City",
        "abilities": ['lightning zap', 'static shield', 'speed dash'],
        "weaknesses": ['Earth', 'Water'],
        "resistances": ['Electric', 'Air'],
        "aggressiveness": 6,
        "intelligence": 7,
        "friendliness": 5,
        "stats": {
            "strength": 6,
            "speed": 8,
            "defense": 4,
            "agility": 7,
            "stamina": 6,
        },
        "catchphrase": "Shock and roll!",
        "class_period": "1st",
        "student_name": "Max",
        "id": "1st_tig1",
        "terrain_boost_used": False,
    },
}
